/*
 * This source file was generated by the Gradle 'init' task
 */
package com.brokenchess;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Application app = new Application();
        assertNotNull(app);
    }
}
